### PR TITLE
Replace CoffeeScript with plain old Javascript

### LINKED ISSUE #13: Replace Coffeescript?
I don't want to go down this road unless its approved, but any reason to not mimic the other more active tree-sitter libraries and just use plain old JavaScript?

### PR DESCRIPTION
**Pull request by justin**
This is a heavy change by nature of switching from CoffeeScript to POSJ. The generated parser remains unchanged at least. 

At a high level this is what I'm doing:

1. Took the generated JS from the `coffee` file and add it to the repo.
2. Touched up the generated file to use arrow function for declarations.
3. Cleaned up the formatting a bit so its more readable going forward.

My JS skills are pretty green, so feedback welcomed if I screwed something up.

Fixes #13.

### CODE REVIEW

**Comment by robrix** [comment]
Thanks so much for the PR!

I’ve requested review from @maxbrunsfeld since I’m probably not qualified to review JS 😊 That said, I am very pleased with this PR; thanks again!

**Comment by maxbrunsfeld** [comment]
This is great. Thanks so much @justin.

**Comment by Arcanemagus** [comment]
For future reference if you ever take on a project like this again I would _highly_ recommend [decaffeinate](https://decaffeinate-project.org/repl/) as it does all that stuff for you automatically, leaving you a little manual cleanup at the end 😉.

**Comment by justin** [comment]
NOW YOU TELL ME. Told you i was green. :-P 

thank you.

**Pull request merged**
