### PR TITLE
[WIP] Expressions

### PR DESCRIPTION
**Pull request by robrix**
- [x] `try`
- [x] prefix operators
- [x] binary operator chains
- [x] postfix operators
- [x] literals
- [ ] numeric literals
- [ ] string literals
- [ ] string interpolation
- [x] flatten the expression productions
- [x] re-enable closures
- [x] re-enable trailing closures
- [ ] test the rest of the expressions

### CODE REVIEW

**Comment by robrix** [comment]
There is significant ambiguity present here, for example between various statements which can be followed by code blocks and which can have expressions present in their clauses: expressions can be closures, and closures conflict with code blocks.

Swift handles this by disallowing (unparenthesized) closures in clauses. We can produce a similar rule (with some effort).

**Comment by robrix** [comment]
Inching towards sanity.

**Comment by maxbrunsfeld** [comment]
@robrix An update on this - These test failures are definitely tree-sitter's fault. The ambiguities that we added on Wednesday exposed two bugs in the tree-sitter runtime library. One of those bugs was trivial and is fixed on master, but that still leaves one test failure due to a second bug. In the `switch statements` test,  tree-sitter isn't correctly handling the ambiguity between the switch statement's body, and a trailing closure for the switch expression.

**Comment by robrix** [comment]
Excellent, thank you so much!

No rush on fixes—I’m going to be focusing on other things for the next week or so anyway.

**Comment by maxbrunsfeld** [comment]
:green_apple:

**Comment by danielmartin** [comment]
What's the status of this PR? I see there's a lot of conflicts because the grammar changes basically need to be ported to the new format.

Maybe it's a better idea to introduce Swift expression support little by little, to simplify code reviews and avoid the typical conflicts from long-running branches.

**Comment by justin** [comment]
FWIW, I’ve been ignoring this one since it’s so dated. I’m working on fixing errors returned while parsing a variety of files lately.

**Comment by robrix** [comment]
Yes, I think it’s best to ignore this PR altogether.

**Pull request closed without merging**
